# Core Settings
xkb_rules_layout=no

# run at startup
exec-once = ~/.config/mango/autostart.sh

# Keybindings: Core Actions
bind=SUPER,r,reload_config
bind=Alt,q,killclient
bind=SUPER+SHIFT,q,quit

# Keybindings: Launchers
bind=Alt,Return,spawn,kitty
bind=Alt,D,spawn,fuzzel

# Keybindings: Workspaces
bind=Alt+SHIFT,1,tag,1
bind=Alt+SHIFT,2,tag,2
bind=Alt+SHIFT,3,tag,3
bind=Alt,1,view,1,0
bind=Alt,2,view,2,0
bind=Alt,3,view,3,0

# Keybindings: Window Management
bind=Alt,Left,focusdir,left
bind=Alt,Right,focusdir,right
bind=Alt,Up,focusdir,up
bind=Alt,Down,focusdir,down
bind=SUPER,f,togglefullscreen
bind=SUPER,v,togglefloating

# Mouse Controls
mousebind=Alt,btn_left,moveresize,curmove
mousebind=Alt,btn_right,moveresize,curresize

# Appearance
borderpx=2
gappih=0
gappiv=0
border_radius=5
border_radius_location_default=0
gappoh=5
gappov=5

# Blur / Transparency
blur=1
blur_layer=1
blur_optimized=0
blur_params_radius=8
blur_params_num_passes=3
blur_params_noise=0.02
blur_params_brightness=0.9
blur_params_contrast=0.9
blur_params_saturation=1
# Since there is no ignore alpha we have to exclude click catcher
layerrule=noblur:1,layer_name:vibepanel-click-catcher

# Display Layout
monitorrule=make:AOC,model:C27G4ZXU,width:1920,height:1080,refresh:280.003,x:0,y:0,scale:1
monitorrule=make:AOC,model:2590G4,width:1920,height:1080,refresh:144.001,x:-1920,y:0,scale:1
monitorrule=name:^eDP-1$,width:2880,height:1800,scale:1.5,refresh:120,x:0,y:0

# Cursor Theme
cursor_size=24
cursor_theme=Bibata-Modern-Classic

# Cycle through layouts
bind=SUPER,1,setlayout,scroller
bind=SUPER,2,setlayout,fair

# hotarea overview
enable_hotarea=1

bind=Alt,space,spawn,playerctl play-pause
