# Keyboard and Input
xkb_rules_layout=no

# Startup
exec-once=~/.config/mango/autostart.sh

# Core Keybindings
bind=SUPER,r,reload_config
bind=Alt,q,killclient
bind=SUPER+SHIFT,q,quit

# Launcher Keybindings
bind=Alt,Return,spawn,kitty
bind=Alt,D,spawn,fuzzel

# Workspace Keybindings
bind=Alt,1,view,1,0
bind=Alt,2,view,2,0
bind=Alt,3,view,3,0
bind=Alt+SHIFT,1,tag,1
bind=Alt+SHIFT,2,tag,2
bind=Alt+SHIFT,3,tag,3

# Window Focus and Management
bind=Alt,Left,focusdir,left
bind=Alt,Right,focusdir,right
bind=Alt,Up,focusdir,up
bind=Alt,Down,focusdir,down
bind=SUPER,f,togglefullscreen

# Mouse Bindings
mousebind=Alt,btn_left,moveresize,curmove
mousebind=Alt,btn_right,moveresize,curresize
mousebind=Alt,btn_middle,togglefloating

# Layout Keybindings
bind=SUPER,1,setlayout,scroller
bind=SUPER,2,setlayout,fair

# Media and Other Controls
bind=Alt,space,spawn,playerctl play-pause

# Display Configuration
monitorrule=make:AOC,model:C27G4ZXU,width:1920,height:1080,refresh:280.003,x:0,y:0,scale:1
monitorrule=make:AOC,model:2590G4,width:1920,height:1080,refresh:144.001,x:-1920,y:0,scale:1
monitorrule=name:^eDP-1$,width:2880,height:1800,scale:1.5,refresh:120,x:0,y:0

# Cursor Theme
cursor_size=24
cursor_theme=Bibata-Modern-Classic

# Window Appearance
borderpx=2
border_radius=4
border_radius_location_default=0
gappih=0
gappiv=0
gappoh=5
gappov=5

# Blur and Transparency
blur=1
blur_layer=1
blur_optimized=0
blur_params_radius=8
blur_params_num_passes=3
blur_params_noise=0.02
blur_params_brightness=0.9
blur_params_contrast=0.9
blur_params_saturation=1
layerrule=noblur:1,layer_name:vibepanel-click-catcher

# UI Features
enable_hotarea=1
