# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x141c2aff
rootcolor = 0x141c2aff
bordercolor = 0x5f6874ff
dropcolor = 0x6798e480
splitcolor = 0xa566ccff
focuscolor = 0x6798e4ff
maximizescreencolor = 0x6a5cd6ff
urgentcolor = 0xd17e6bff
scratchpadcolor = 0xa566ccff
globalcolor = 0x0c3e8dff
overlaycolor = 0x1b106fff
