[bar]
outputs = ["DP-3", "eDP-1"]
position = "top"
size = 32
border_radius = 30
background_opacity = 0

[widgets]
left = ["workspaces", "window_title"]
center = ["media", "clock"]
right = ["tray", "updates", "custom-weather", "cpu", "quick_settings", "battery", "notifications"]
border_radius = 16
background_opacity = 0.5

[widgets.clock]
format = "%d.%m.%Y %H:%M"
outline_color = "accent"

[widgets.media]
art_radius = 4

[widgets.updates]
check_interval = 3600
terminal = "kitty"

[widgets.custom-weather]
exec = "curl -s 'wttr.in/?format=1'"
template = " {output}"
interval = 600
on_click = "xdg-open https://wttr.in"
tooltip = "Weather"
max_chars = 30

[theme]
shadows = false
mode = "auto"
scheme = "dark"
animations = false
ripple = false

[theme.icons]
theme = "material"
weight = 400

[osd]
enabled = true
position = "bottom"
show_value = false

[advanced]
compositor = "mango"
